# Generated by Django 3.2 on 2021-04-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компетенции')),
            ],
        ),
        migrations.CreateModel(
            name='EdOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название образовательной организации')),
            ],
        ),
        migrations.CreateModel(
            name='EmpCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации-работодателя')),
            ],
        ),
        migrations.CreateModel(
            name='EmpCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компетенции')),
                ('ed_competence', models.ManyToManyField(blank=True, related_name='ed_to_emp_competence', to='main_app.EdCompetence')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование стажировки')),
                ('description', models.TextField(verbose_name='Описание практики')),
                ('ed_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edorganization', verbose_name='Образовательная организация')),
                ('input_ed_competence', models.ManyToManyField(related_name='input_ed_competence', to='main_app.EdCompetence')),
                ('output_ed_competence', models.ManyToManyField(related_name='output_ed_competence', to='main_app.EdCompetence')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование стажировки')),
                ('description', models.TextField(verbose_name='Описание стажировки')),
                ('emp_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.empcompany', verbose_name='Работодатель')),
                ('input_emp_competence', models.ManyToManyField(related_name='input_emp_competence', to='main_app.EmpCompetence')),
                ('output_emp_competence', models.ManyToManyField(related_name='output_emp_competence', to='main_app.EmpCompetence')),
            ],
        ),
        migrations.AddField(
            model_name='edcompetence',
            name='emp_competence',
            field=models.ManyToManyField(blank=True, related_name='emp_to_ed_competence', to='main_app.EmpCompetence'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edcompetence')),
                ('ed_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edorganization')),
            ],
        ),
    ]
