# Generated by Django 3.2 on 2021-04-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empcompany',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Оценка'),
        ),
    ]
