# Generated by Django 3.2 on 2021-04-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20210417_0319'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ManyToManyField(to='main_app.Practice')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edorganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_user.studentmore')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edorganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_user.edworkermore')),
            ],
        ),
        migrations.AlterField(
            model_name='edcompetence',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название компетенции'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='approvalpractice',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
