# Generated by Django 3.2 on 2021-04-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdWorkerM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.empcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_user.edworkermore')),
            ],
        ),
    ]
