# Generated by Django 3.2 on 2021-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210417_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='edorganization',
            name='competence',
            field=models.ManyToManyField(to='main_app.EdCompetence'),
        ),
        migrations.DeleteModel(
            name='ApprovalPractice',
        ),
    ]
