# Generated by Django 3.2 on 2021-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_edworkerm'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
