# Generated by Django 3.2 on 2021-04-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_internshipapplication_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='applied',
            new_name='accepted',
        ),
    ]
