# Generated by Django 3.2 on 2021-04-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_applied_internshipapplication_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.practice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentm')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentm')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
