# Generated by Django 3.2 on 2021-04-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210417_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOnStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отзыва')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.worker', verbose_name='Работодатель')),
                ('student_for_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentm', verbose_name='Отзыв на студента')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOnEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок отзыва')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('employer_for_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.empcompany', verbose_name='Отзыв о работодателе')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentm', verbose_name='Студент')),
            ],
        ),
    ]
