# Generated by Django 3.2 on 2021-04-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_reviewonemployer_reviewonstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empcompetence',
            name='ed_competence',
        ),
    ]
