# Generated by Django 3.2 on 2021-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_name_skill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewonemployer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviewonstudent',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Оценка'),
        ),
    ]
