# Generated by Django 3.2 on 2021-04-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210417_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewonemployer',
            name='employer_for_review',
        ),
        migrations.AddField(
            model_name='reviewonemployer',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.internship', verbose_name='Отзыв о стажировке'),
            preserve_default=False,
        ),
    ]
