# Generated by Django 3.2 on 2021-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_empcompetence_ed_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcompetence',
            name='emp_competence',
            field=models.ManyToManyField(blank=True, to='main_app.EmpCompetence'),
        ),
    ]
