# Generated by Django 3.2 on 2021-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210417_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentm',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Оценка'),
        ),
    ]
