# Generated by Django 3.2 on 2021-04-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_edcompetence_emp_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='ed_organization',
        ),
        migrations.AddField(
            model_name='reviewonemployer',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='reviewonstudent',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emp_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.empcompany'),
            preserve_default=False,
        ),
    ]
