# Generated by Django 3.2 on 2021-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210417_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empcompetence',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название компетенции'),
        ),
    ]
