# Generated by Django 3.2 on 2021-04-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20210417_0319'),
        ('main_app', '0010_alter_empcompetence_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='EmployerM',
        ),
    ]
