# Generated by Django 3.2 on 2021-04-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20210417_0319'),
        ('main_app', '0011_rename_worker_employerm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_user.employermore'),
        ),
    ]
