# Generated by Django 3.2 on 2021-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_employerm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='students',
            field=models.ManyToManyField(to='main_app.StudentM'),
        ),
    ]
