# Generated by Django 3.2 on 2021-04-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_remove_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employermore',
            name='ed_organization',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='ed_organization',
        ),
    ]
