# Generated by Django 3.2 on 2021-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('EMPLOYER', 'Employer'), ('EDWORKER', 'Edworker')], max_length=15, verbose_name='Type'),
        ),
    ]
